package atruns

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/patiently/anti-tangent-mcp/gnome-topbar/daemon/internal/bm"
	"github.com/patiently/anti-tangent-mcp/scorecard"
)

const (
	noteSchema    = 1
	noteDirectory = "anti-tangent/runs"
)

// ShareEnabled reports whether this daemon publishes its runs. Anything but
// exactly "1" is off, so a stray "true" or "yes" never starts sharing.
func ShareEnabled(getenv func(string) string) bool { return getenv("ANTI_TANGENT_SHARE_STATS") == "1" }

type notePayload struct {
	Schema    int                     `json:"schema"`
	Publisher string                  `json:"publisher"`
	Lines     []scorecard.RunLine     `json:"lines"`
	Outcomes  []scorecard.OutcomeLine `json:"outcomes"`
}

// NoteBody renders one run's records as an at_run note. Only scorecard
// records go in; they are content-free by construction, and titles from
// Data.Titles are never passed here.
func NoteBody(publisher string, lines []scorecard.RunLine, outcomes []scorecard.OutcomeLine) (string, error) {
	// Categories and model strings are bounded again here, on copies, because
	// this is the last point before the text leaves the machine: a
	// hand-edited or older outcomes.jsonl line must not publish a finding
	// description or an unbounded model string.
	clean := make([]scorecard.OutcomeLine, len(outcomes))
	for i, o := range outcomes {
		o.Findings = append([]scorecard.OutcomeFinding(nil), o.Findings...)
		for k := range o.Findings {
			o.Findings[k].Category = scorecard.NormalizeCategory(o.Findings[k].Category)
		}
		o.ReviewerModel = scorecard.ClampModelString(o.ReviewerModel)
		o.ImplementerModels = append([]scorecard.ImplementerModel(nil), o.ImplementerModels...)
		for k := range o.ImplementerModels {
			o.ImplementerModels[k].Model = scorecard.ClampModelString(o.ImplementerModels[k].Model)
		}
		clean[i] = o
	}
	b, err := json.MarshalIndent(notePayload{Schema: noteSchema, Publisher: publisher, Lines: lines, Outcomes: clean}, "", "  ")
	if err != nil {
		return "", err
	}
	return "anti-tangent run record (content-free; generated by gnome-topbar).\n\n```json\n" + string(b) + "\n```\n", nil
}

// ParseNote extracts a note's records and stamps every one with the note's
// publisher, so a pooled record cannot claim another publisher.
func ParseNote(body string) ([]scorecard.RunLine, []scorecard.OutcomeLine, error) {
	start := strings.Index(body, "```json\n")
	if start < 0 {
		return nil, nil, errors.New("no json block")
	}
	rest := body[start+len("```json\n"):]
	end := strings.Index(rest, "\n```")
	if end < 0 {
		return nil, nil, errors.New("unterminated json block")
	}
	var p notePayload
	if err := json.Unmarshal([]byte(rest[:end]), &p); err != nil {
		return nil, nil, err
	}
	if p.Schema != noteSchema || p.Publisher == "" {
		return nil, nil, fmt.Errorf("unsupported note: schema %d, publisher %q", p.Schema, p.Publisher)
	}
	for i := range p.Lines {
		p.Lines[i].Publisher = p.Publisher
	}
	for i := range p.Outcomes {
		p.Outcomes[i].Publisher = p.Publisher
	}
	return p.Lines, p.Outcomes, nil
}

type Publisher struct {
	Client    *bm.Client
	Project   string
	Username  string
	StatePath string
}

// Publish writes every run with at least one outcome whose note body changed
// since the last successful publish. It returns how many notes it wrote.
func (p *Publisher) Publish(ctx context.Context, d Data) (int, error) {
	published := loadPublished(p.StatePath)
	lines := map[string][]scorecard.RunLine{}
	for _, l := range d.Lines {
		lines[l.RunHash] = append(lines[l.RunHash], l)
	}
	outs := map[string][]scorecard.OutcomeLine{}
	for _, o := range d.Outcomes {
		outs[o.RunHash] = append(outs[o.RunHash], o)
	}
	wrote := 0
	var firstErr error
	for hash, ocs := range outs {
		body, err := NoteBody(p.Username, lines[hash], ocs)
		if err != nil {
			continue
		}
		sum := sha256.Sum256([]byte(body))
		digest := hex.EncodeToString(sum[:])
		if published[hash] == digest {
			continue
		}
		if err := p.Client.WriteRunNote(ctx, p.Project, noteDirectory, hash, body); err != nil {
			if firstErr == nil {
				firstErr = err
			}
			continue
		}
		published[hash] = digest
		wrote++
	}
	if wrote > 0 {
		savePublished(p.StatePath, published)
	}
	return wrote, firstErr
}

func loadPublished(path string) map[string]string {
	m := map[string]string{}
	if b, err := os.ReadFile(path); err == nil {
		_ = json.Unmarshal(b, &m)
	}
	return m
}

func savePublished(path string, m map[string]string) {
	b, err := json.Marshal(m)
	if err != nil {
		return
	}
	_ = os.MkdirAll(filepath.Dir(path), 0o755)
	tmp := path + ".tmp"
	if os.WriteFile(tmp, b, 0o600) == nil {
		_ = os.Rename(tmp, path)
	}
}
